protected/modules/admin/models/SettingsForm.php
<?php
class SettingsForm extends CFormModel {
	public $breadcrumbsEnabled;
	public function rules() {
		return array(
			array('breadcrumbsEnabled','required'),
			//array('breadcrumbsEnabled','numerical','integerOnly'=>true),
		);
	}
}
?>

protected/modules/admin/controllers/DefaultController.php
<?php

class DefaultController extends Controller
{
	public $defaultAction='dashboard';
	
	public function filters() {
		return array(
			'accessControl',
		);
	}
	
	public function accessRules() {
		return array(
			array(
				'allow',
				'users'=>array('@'),
			),
			array('deny'),
		);
	}
	
	public function actionDashboard() {
		$this->layout='main';
		$this->render('dashboard',array('assetsUrl'=>$this->module->params->assetsUrl));
	}
	
	public function actionApplicants($do=null,$id=null) {
		$this->layout='main';
		switch($do){
			case 'view':
				$this->renderText('Просмотр анкеты №'.$id);
				break;
			case 'delete':
				$this->renderText('Удаление анкеты №'.$id);
				break;
			default:
				$applicants = new CActiveDataProvider('Applicants',array(
					'criteria'=>array(
						'select'=>array(
							'id',
							'fullname',
							'vacancy',
						),
					),
				));
				$this->render('applicants',array('applicants'=>$applicants));
		}
	}
	
	public function actionVacancies($do=null,$id=null) {
		$this->asideMenu = array(
			array('label'=>'Добавить вакансию','url'=>array('/admin/default/vacancies','do'=>'create')),
		);
		switch($do){
			case 'create':
				$this->breadcrumbs = array(
					'Панель управления'=>array('/admin'),
					'Открытые вакансии'=>array('/admin/default/vacancies'),
					'Добавление вакансии'
				);
				$model=new Vacancies;
				if(isset($_POST['Vacancy'])) {
					$model->attributes=$_POST['Vacancy'];
					if($model->save())
						$this->redirect(array('/admin/vacancies'));
				}
				$this->render('vacancyForm',array('model'=>$model));
				break;
			case 'update':
				$this->breadcrumbs = array(
					'Панель управления'=>array('/admin'),
					'Открытые вакансии'=>array('/admin/default/vacancies'),
					'Обновление вакансии'
				);
				$model=Vacancies::model()->findByPk($id);
				if($model===null) throw new CHttpException(404,'The requested page does not exist.');
				if(isset($_POST['Vacancy'])) {
					$model->attributes=$_POST['Vacancy'];
					if($model->save())
						$this->redirect(array('/admin/vacancies'));
				}
				$this->render('vacancyForm',array('model'=>$model));
				break;
			case 'delete':
				Vacancies::model()->findByPk($id)->delete();
				$this->redirect(array('/admin/vacancies'));
				break;
			default:
				$this->breadcrumbs = array(
					'Панель управления'=>array('/admin'),
					'Открытые вакансии',
				);
				$vacancies = new CActiveDataProvider('Vacancies');
				$this->render('vacancies',array('vacancies'=>$vacancies));
		}
	}
	
	public function actionSettings() {
		$settingsFile=$this->module->basePath.DIRECTORY_SEPARATOR.$this->module->params->settingsFile;
		$model=new SettingsForm;
		if(isset($_POST['SettingsForm'])) {
			$model->attributes=$_POST['SettingsForm'];
			if($model->validate()) {
				$fp=@fopen($settingsFile,'w');
				@flock($fp,LOCK_EX);
				@fwrite($fp,CJSON::encode($model->attributes));
				@flock($fp,LOCK_UN);
				@fclose($fp);
				Yii::app()->user->setFlash('settingsValidationSuccess','Настройки сохранены.');
				$this->refresh();
			} else {				
				Yii::app()->user->setFlash('settingsValidationError','Валидация не прошла.');
			}
		} else {
			$model->attributes=CJSON::decode(file_get_contents($settingsFile,true));
		}
		$this->render('settings',array('model'=>$model));
	}
}

protected/modules/admin/views/default/applicants.php
<?php
	$this->breadcrumbs = array(
		$this->module->params->name => array('/admin'),
		'Заполненные анкеты',
	);
	$this->asideMenu = array(
		array('label'=>'Создать анкету','url'=>array('/admin/applicants','id'=>2)),
	);
?>
<?php
	$this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$applicants,
		'columns'=>array(
			'id',
			'fullname',
			'vacancy',
			array(
				'class'=>'CLinkColumn',
				'label'=>'Подробнее',
				'urlExpression'=>'Yii::app()->controller->createUrl("default/applicants",array("do"=>"view","id"=>$data->id))',
			),
		),
		'htmlOptions'=>array(
			'style'=>'padding:0;',
		),
		'template'=>'{items}{pager}',
		'enableSorting'=>false,
		'selectableRows'=>0,
	));
?>

protected/modules/admin/views/default/dashboard.php
<?php
$this->breadcrumbs=array(
	$this->module->params->name,
);
?>
<ul id="dashboardBlocks" class="cf">
	<li>
		<a href="<?php echo $this->createUrl('default/applicants'); ?>" class="thumbnail">
			<img src="<?php echo $assetsUrl ?>/img/icon-emails.png" class="dashboard-block-icon">
			<span class="dashboard-block-headline">Заполненные анкеты</span>
			<span class="dashboard-block-description">Список всех заполненных анкет</span>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->createUrl('default/vacancies'); ?>" class="thumbnail">
			<img src="<?php echo $assetsUrl ?>/img/icon-vacancies.png" class="dashboard-block-icon">
			<span class="dashboard-block-headline">Открытые вакансии</span>
			<span class="dashboard-block-description">Добавление/удаление вакансий компании</span>
		</a>
	</li>
	<!--
	-->
	<li>
		<a href="<?php echo $this->createUrl('default/settings'); ?>" class="thumbnail">
			<img src="<?php echo $assetsUrl ?>/img/icon-tools.png" class="dashboard-block-icon">
			<span class="dashboard-block-headline">Настройки</span>
			<span class="dashboard-block-description">Настройки приложения</span>
		</a>
	</li>
</ul>

protected/modules/admin/views/default/settings.php
<?php echo Yii::app()->user->getFlash('settingsValidationSuccess'); ?>
<?php echo Yii::app()->user->getFlash('settingsValidationError'); ?>
<form id="settingsForm" method="post" action="">
	<p>
		<label>Навигационная цепочка:</label>
		<?php
			echo CHtml::activeRadioButtonList(
				$model,
				'breadcrumbsEnabled',
				array(
					1=>'Включена',
					0=>'Выключена',
				)
			);
		?>
		<!--
		<label for="inputBreadcrumbsEnabled"><input type="radio" id="inputBreadcrumbsEnabled" name="Settings[breadcrumbsEnabled]" value="0" checked> Включена</label>
		<label for="inputBreadcrumbsDisabled"><input type="radio" id="inputBreadcrumbsDisabled" name="Settings[breadcrumbsEnabled]" value="1"> Выключена</label>
		-->
	</p>
	
	<p><button type="submit" class="btn btn-big btn-round">Сохранить</button></p>
</form>

protected/modules/admin/views/default/vacancies.php
<?php
	$this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$vacancies,
		'columns'=>array(
			array(
				'name'=>'Вакансия',
				'value'=>'$data->title',
			),
			array(
				'class'=>'CLinkColumn',
				'label'=>'Изменить',
				'urlExpression'=>'Yii::app()->controller->createUrl("/admin/default/vacancies",array("do"=>"update","id"=>$data->id))',
				'htmlOptions'=>array(
					'style'=>'width:60px;text-align:center;',
				),
			),
			array(
				'class'=>'CLinkColumn',
				'label'=>'Удалить',
				'urlExpression'=>'Yii::app()->controller->createUrl("/admin/default/vacancies",array("do"=>"delete","id"=>$data->id))',
				'htmlOptions'=>array(
					'style'=>'width:60px;text-align:center;',
				),
			),
		),
		'htmlOptions'=>array(
			'style'=>'padding:0;font-size:12px;',
		),
		'template'=>'{items}{pager}',
		'enableSorting'=>false,
		'selectableRows'=>0,
	));
?>

protected/modules/admin/views/default/vacancyForm.php
<?php
/* @var $this VacanciesController */
/* @var $model Vacancies */
/* @var $form CActiveForm */
?>

<div class="flash"><?php echo Yii::app()->user->getFlash('vacancySaveErrors') ?></div>
<form id="vacancyForm" method="post" action="">
	<p>
		<label for="inputVacancyTitle">Название вакансии:</label>
		<input type="text" id="inputVacancyTitle" name="Vacancy[title]" value="<?php echo $model->title ?>" style="width:250px;font-size:12px;">
	</p>
	<p>
		<button type="submit" class="btn btn-big btn-round">Создать</button>
	</p>
</form>

protected/modules/admin/views/layouts/html.php
<?php
	$module = $this->module;
	$params = $module->params;
	$headTitle = $params->name.' – '.CHtml::encode($this->pageTitle);
	$navMenu = '';
	if (!empty($params->navMenu))
		$navMenu = $this->widget('zii.widgets.CMenu', array('items'=>$params->navMenu, 'id'=>'navMenu'), true);
?>
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="<?php echo $params->faviconUrl ?>" type="image/x-icon">
		<link rel="stylesheet" href="<?php echo $params->assetsUrl ?>/css/bubble.css">
		<link rel="stylesheet" href="<?php echo $params->assetsUrl ?>/css/main.css">
		<link rel="stylesheet" href="<?php echo $params->assetsUrl ?>/fonts/opensans.css">
		<title><?php echo $headTitle ?></title>
		<!--[if lt IE 9]>
		<script src="<?php echo $params->assetsUrl ?>/js/html5shiv.js"></script>
		<![endif]-->
	</head>
	<body>
		<div id="wrap">
			<header>
				<nav class="cf">
					<div id="navBrand">
						<a href="<?php echo $params->homeUrl ?>"><?php echo $params->name ?></a>
					</div>
					<?php echo $navMenu ?>
					<ul id="navUserMenu">
						<li><a href="<?php echo Yii::app()->homeUrl ?>"><img src="<?php echo $params->assetsUrl ?>/img/icon-exit.png"> Перейти на сайт</a></li>
					</ul>
				</nav>
			</header>
			<div id="page" class="cf">
				<?php echo $content ?>
			</div>
		</div>
		<footer>
			<div class="inner"><table><tr><td>
				&copy; 2013<?php if(date('Y')!='2013') echo '-'.date('Y') ?> <?php echo Yii::app()->name ?>
			</td></tr></table></div>
		</footer>
		
		<script src="<?php echo $params->assetsUrl ?>/js/main.js"></script>
	</body>
</html>

protected/modules/admin/views/layouts/main-aside.php
<?php $this->beginContent('/layouts/html') ?>
	<div id="main">
		<div class="inner">
			<?php echo $this->breadcrumbs ?>
			<?php echo $content ?>
		</div>
	</div>
	<aside>
		<?php echo $this->asideMenu ?>
	</aside>
<?php $this->endContent() ?>

protected/modules/admin/views/layouts/main.php
<?php $this->beginContent('/layouts/html') ?>
	<?php echo $this->breadcrumbs ?>
	<?php echo $content ?>
<?php $this->endContent() ?>